apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tmk7d61uv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tmk7d61uv-python 
  name: tmk7d61uv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tmk7d61uv-python 
